apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: 292090429255.dkr.ecr.ap-south-1.amazonaws.com/eks:latest
        name: guestbook-ui
        ports:
        - containerPort: 80
